# Site settings
title: Fitnesscentrumnoord
email: info@fitnesscentrumnoord.nl
description: > # this means to ignore newlines until "baseurl:"
  We beperken ons tot de essentie van het trainen met resultaat, door simpelweg aan de slag te gaan. 
  Verantwoord bewegen moet je nog altijd zelf doen geen machine, hoe imposant dan ook, kan dat voor jou doen. 
  Uiteraard kunnen wij je daarbij deskundig ondersteunen.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fitnesscentrumnoord.nl" # the base hostname & protocol for your site
baseheaderimg: /images/defaultheader.png

# Build settings
markdown: kramdown

menus:
    main:
    - Home: /
    - Trainingen: /trainingen/
    - Voeding: /voeding/
    - Verstand en gevoel: /verstand-en-gevoel/
    - Fitnesscentrumnoord: /fitnesscentrumnoord/
    - contact: /fitnesscentrumnoord/contact/